name: 'empathic-credit-system'

services:
  emotion-ingestion-service-nginx:
    image: nginx:1.25.4-alpine
    container_name: emotion-ingestion-service-nginx
    volumes:
      - ./services/emotion-ingestion-service/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      emotion-ingestion-service:
        condition: service_healthy
    networks:
      - empathic-network

  emotion-ingestion-service:
    hostname: emotion-ingestion-service
    image: empathic-credit-system/emotion-ingestion-service
    restart: on-failure
    # env_file: ./services/emotion-ingestion-service/.env
    networks:
      - empathic-network
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  empathic-network:
    driver: bridge
