name: 'empathic-credit-system'

services:
  # APIs and Workers
  emotion-ingestion-service-nginx:
    image: nginx:1.25.4-alpine
    container_name: emotion-ingestion-service-nginx
    volumes:
      - ./services/emotion-ingestion-service/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      emotion-ingestion-service:
        condition: service_healthy
    networks:
      - emotion-ingestion-service-network

  emotion-ingestion-service:
    hostname: emotion-ingestion-service
    image: empathic-credit-system/emotion-ingestion-service
    restart: on-failure
    environment:
      NATS_URL: nats://nats:4222
    networks:
      - emotion-ingestion-service-network
      - nats-network
    depends_on:
      nats:
        condition: service_healthy
      nats-stream-provisioner:
        condition: service_completed_successfully
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  emotion-processing-worker:
    image: empathic-credit-system/emotion-processing-worker
    restart: on-failure
    environment:
      NATS_URL: nats://nats:4222
      DATABASE_URL: "postgresql://ecsuser:ecspassword@ecs-postgres:5432/ecsdb"
    networks:
      - nats-network
      - ecs-postgres-network
    depends_on:
      nats:
        condition: service_healthy
      nats-stream-provisioner:
        condition: service_completed_successfully
      ecs-postgres:
        condition: service_healthy
    deploy:
      replicas: 1

  transaction-service-nginx:
    image: nginx:1.25.4-alpine
    container_name: transaction-service-nginx
    volumes:
      - ./services/transaction-service/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8888:8888"
    networks:
      - transaction-service-network
    depends_on:
      transaction-service:
        condition: service_healthy
  
  transaction-service:
    hostname: transaction-service
    image: empathic-credit-system/transaction-service
    restart: on-failure
    environment:
      NATS_URL: nats://nats:4222
    networks:
      - transaction-service-network
      - nats-network
    depends_on:
      nats:
        condition: service_healthy
      nats-stream-provisioner:
        condition: service_completed_successfully
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  transaction-processing-worker:
    image: empathic-credit-system/transaction-processing-worker
    restart: on-failure
    environment:
      NATS_URL: nats://nats:4222
      DATABASE_URL: "postgresql://ecsuser:ecspassword@ecs-postgres:5432/ecsdb"
    networks:
      - nats-network
      - ecs-postgres-network
    depends_on:
      nats:
        condition: service_healthy
      nats-stream-provisioner:
        condition: service_completed_successfully
      ecs-postgres:
        condition: service_healthy
    deploy:
      replicas: 2

  credit-analysis-service:
    image: empathic-credit-system/credit-analysis-service
    restart: on-failure
    networks:
      - credit-analysis-service-network
    deploy:
      replicas: 2

  # Messaging
  nats:
    image: nats:2.10.17-alpine
    container_name: nats-server
    command: -js
    networks:
      - nats-network
    healthcheck:
      test: ["CMD", "nats-server", "-v"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats-stream-provisioner:
    image: synadia/nats-box
    container_name: nats-stream-provisioner
    networks:
      - nats-network
    depends_on:
      nats:
        condition: service_healthy
    entrypoint: >
      sh -c "
        until nats --server nats:4222 stream info emotions > /dev/null 2>&1; do
          echo 'Tentando criar o stream emotions...'
          nats --server nats:4222 stream add emotions --subjects user.emotions.topic --storage memory --retention limits --discard old --dupe-window 2m --max-msgs=-1 --max-bytes=-1 --max-age=0s --max-msg-size=-1 --replicas 1
          sleep 2
        done

        until nats --server nats:4222 stream info transactions > /dev/null 2>&1; do
          echo 'Tentando criar o stream transactions...'
          nats --server nats:4222 stream add transactions --subjects transactions.topic --storage file --retention limits --discard old --dupe-window 2m --max-msgs=-1 --max-bytes=-1 --max-age=0s --max-msg-size=-1 --replicas 1
          sleep 2
        done
      "
    restart: on-failure

  # Databases
  ecs-postgres:
    image: postgres:16-alpine
    container_name: ecs-postgres
    restart: always
    environment:
      POSTGRES_USER: ecsuser
      POSTGRES_PASSWORD: ecspassword
      POSTGRES_DB: ecsdb
    volumes:
      - emotion_postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - ecs-postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecsuser -d ecsdb"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

# Application networks
networks:
  emotion-ingestion-service-network:
    driver: bridge
  transaction-service-network:
    driver: bridge
  credit-analysis-service-network:
    driver: bridge
  nats-network:
    internal: true
  ecs-postgres-network:
    internal: true

# Application volumes
volumes:
  emotion_postgres_data:
  transaction_postgres_data:
