name: 'empathic-credit-system'

services:
  # Emotion Ingestion Service containers
  emotion-ingestion-service-nginx:
    image: nginx:1.25.4-alpine
    container_name: emotion-ingestion-service-nginx
    volumes:
      - ./services/emotion-ingestion-service/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      emotion-ingestion-service:
        condition: service_healthy
    networks:
      - emotion-ingestion-service-network

  emotion-ingestion-service:
    hostname: emotion-ingestion-service
    image: empathic-credit-system/emotion-ingestion-service
    restart: on-failure
    environment:
      NATS_URL: nats://nats:4222
    networks:
      - emotion-ingestion-service-network
      - nats-network
    depends_on:
      nats:
        condition: service_healthy
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  nats:
    image: nats:2.10.17-alpine
    container_name: nats-server
    command: -js
    networks:
      - nats-network
    healthcheck:
      test: ["CMD", "nats-server", "-v"]
      interval: 10s
      timeout: 5s
      retries: 5
    # To check the configuration, run in another terminal: 
    # docker run --rm -it --network empathic-credit-system_nats-network synadia/nats-box

  # Emotion Processing Worker containers
  emotion-processing-worker:
    image: empathic-credit-system/emotion-processing-worker
    restart: on-failure
    environment:
      NATS_URL: nats://nats:4222
    networks:
      - nats-network
    depends_on:
      nats:
        condition: service_healthy
    deploy:
      replicas: 2

networks:
  emotion-ingestion-service-network:
    driver: bridge

  nats-network:
    internal: true
